# Generated by Django 4.2.7 on 2023-12-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vacancy",
                    models.CharField(
                        choices=[("Python-разработчик", "Python-разработчик")],
                        max_length=50,
                        verbose_name="выбранная вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "навык",
                "verbose_name_plural": "навыки",
            },
        ),
    ]
