# Generated by Django 4.2.7 on 2023-12-11 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pyskill", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mail_to_send",
                    models.EmailField(
                        max_length=254, verbose_name="почта для рассылки"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="дата начала рассылки")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("раз в месяц", "Раз в месяц"),
                            ("раз в 3 месяца", "Раз в 3 месяца"),
                            ("раз в полгода", "Раз в полгода"),
                            ("раз в год", "Раз в год"),
                        ],
                        max_length=50,
                        verbose_name="периодичность рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("завершена", "Завершена"),
                            ("создана", "Создана"),
                            ("запущена", "Запущена"),
                        ],
                        max_length=150,
                        verbose_name="статус рассылки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
