# Generated by Django 4.2.7 on 2023-12-11 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyskill", "0002_dispatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatch",
            name="start_date",
            field=models.DateField(
                default=datetime.date(2023, 12, 11), verbose_name="дата начала рассылки"
            ),
        ),
    ]
