# Generated by Django 4.2.7 on 2023-12-11 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pyskill", "0003_alter_dispatch_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatch",
            name="status",
        ),
    ]
