# Generated by Django 4.2.7 on 2023-12-11 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pyskill", "0004_remove_dispatch_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatch",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="dispatch",
            name="start_date",
        ),
    ]
