# Generated by Django 4.2.7 on 2023-12-12 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pyskill", "0005_remove_dispatch_frequency_remove_dispatch_start_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
