# Generated by Django 4.2.7 on 2023-12-12 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pyskill", "0006_delete_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispatch",
            name="user",
        ),
    ]
